schema_version = "1.0.0"
id = "faidlix_batch_clean_key"
version = "1.2.0"
name = "Faidlix_BatchCleanKey"
tagline = "Batch clean, delete or decimate keys for selected bones"
maintainer = "Faidlix"
type = "add-on"
blender_version_min = "5.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths = ["__init__.py", "core.py", "ui.py", "README.md"]
