schema_version = "1.0.0"
id = "blander_peferance"
version = "1.1.0"
name = "Blander Peferance"
tagline = "Keep UI defaults and toggle Traditional Chinese"
maintainer = "Faidlix"
type = "add-on"
blender_version_min = "5.1.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths = [
    "__init__.py",
    "translations.py",
    "README.md",
]
