schema_version = "1.0.0"
id = "faidlix_weight"
version = "1.3.0"
name = "Faidlix_Weight"
tagline = "Mirror selected vertex weights with left and right name matching"
maintainer = "Faidlix"
type = "add-on"
blender_version_min = "5.2.0"
license = ["SPDX:GPL-3.0-or-later"]
