schema_version = "1.0.0"
id = "faidlix_fbx_zip_exporter"
version = "1.8.1"
name = "Faidlix_Fbx ZipExporter"
tagline = "Export selected actions and material textures to FBX ZIP"
maintainer = "Faidlix"
type = "add-on"
blender_version_min = "5.2.0"
license = ["SPDX:MIT"]

[build]
paths = [
    "__init__.py",
    "README.md",
]
