schema_version = "1.0.0"
id = "faidlix_outliner"
version = "0.2.16"
name = "Faidlix_Outliner"
tagline = "Select object and collection hierarchies from the Outliner"
maintainer = "Faidlix"
type = "add-on"
blender_version_min = "5.2.0"
license = ["SPDX:GPL-3.0-or-later"]

[build]
paths = [
    "__init__.py",
    "core.py",
    "README.md",
]

